<?php

    function http_request($url)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        $TOKEN = file_get_contents('private/IBM_TOKEN.txt');

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . $TOKEN);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }
    
    function classifyImage($url)
    {
        $response = http_request('https://api.us-south.visual-recognition.watson.cloud.ibm.com/instances/7078e9e4-5603-40ad-a013-816484b75a07/v3/classify?url=' . $url . '&version=2018-03-19');
        $data = json_decode($response);
        $extraction = $data->images[0]->classifiers[0]->classes;
    
        $i = 0;
        while($i < count($extraction)) {
            if ($extraction[$i]->class == 'cat') {
                $animal = "cat";
            break;
            } elseif ($extraction[$i]->class == 'dog'){
                $animal = "dog";
                $score = $extraction[$i]->score;
            break;
            } else {
                $animal = "bukan anjing atau kucing";
                $score = $extraction[$i]->score;
            }
            $i++;
        }

        $classification = [
            'animal'    => $animal,
            'score'     => $score
        ];
    
        return (object) $classification;
    }
    