<?php

    // function http_request($url)
    // {
    //     // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    //     $ch = curl_init();

    //     curl_setopt($ch, CURLOPT_URL, $url);
    //     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    //     curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    //     curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . 'UWoEyJRaroBeTvuFEwwJX8hs5QulsRp4hoUUr12Q98XS');

    //     $result = curl_exec($ch);
    //     if (curl_errno($ch)) {
    //         echo 'Error:' . curl_error($ch);
    //     }
    //     curl_close($ch);

    //     return $result;
    // }
    // $response = http_request('https://api.us-south.visual-recognition.watson.cloud.ibm.com/instances/7078e9e4-5603-40ad-a013-816484b75a07/v3/classify?url=https://post.healthline.com/wp-content/uploads/sites/3/2020/02/322868_1100-732x549.jpg&version=2018-03-19');

    // file_put_contents('response_dog.json', $response);
    // $response_cat = file_get_contents('response_cat.json');
    $response = file_get_contents('response_cat.json');
    

    // $data_cat = json_decode($response_cat);

    $data = json_decode($response);

    // $extraction_cat = $data_cat->images[0]->classifiers[0]->classes;
    $extraction = $data->images[0]->classifiers[0]->classes;
    // echo "<pre>";
    // print_r($extraction);
    // echo "</pre>";

    // echo $extraction[0]->class;
    // echo count($extraction);
    // print_r($extraction);

    $i = 0;
    while($i < count($extraction)) {
        // echo $extraction[$i]->class;
        // echo "<br>";
        if ($extraction[$i]->class == 'cat') {
            $animal = "cat";
        break;
        } elseif ($extraction[$i]->class == 'dog'){
            $animal = "dog";
        break;
        } else {
            $animal = "tidak diketahui";
        }
        $i++;
    }

    echo "<br>";
    echo $animal;